In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("Data set for DADS June.csv")

print(df.head())

          Date   Time                       Description   Type  Amount  \
0   2024-01-01  03:11                AMAZON SELLER SVCS  Debit   ₹2462
1    01-Jan-24  05:44                         BHIM-BMTC     DR   50.00
2    01-Jan-24  09:35  NEFT-TECHCRUSH LABS-SALARY MAY24     CR  ₹84728
3   2024-01-01  14:07              UPI-AMAN-8934@OKAXIS  Debit   ₹1828
4  01 Jan 2024  14:23                      BHIM-BLINKIT  Debit  270.00

    Balance  Mode        Ref
0  678275.0   UPI  TXN190872
1  681007.0   UPI  TXN143064
2  484728.0  NEFT  TXN246316
3 -748745.0   UPI  TXN569226
4  680737.0   UPI  TXN968962

In [ ]:
print(df.shape)

print(df.columns)

print(df.info())

(1328, 8)
Index(['Date', 'Time', 'Description', 'Type', 'Amount', 'Balance', 'Mode',
       'Ref'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1328 entries, 0 to 1327
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         1328 non-null   object
 1   Time         1328 non-null   object
 2   Description  1328 non-null   object
 3   Type         1328 non-null   object
 4   Amount       1328 non-null   object
 5   Balance      1328 non-null   float64
 6   Mode         1328 non-null   object
 7   Ref          1328 non-null   object
dtypes: float64(1), object(7)
memory usage: 83.1+ KB
None

In [ ]:
def convert_date(x):
    formats = [
        "%Y-%m-%d",
        "%d-%b-%y",
        "%d %b %Y",
        "%d/%m/%y"
    ]

    for fmt in formats:
        try:
            return pd.to_datetime(x, format=fmt)
        except:
            continue

    return pd.NaT

df["Date"] = df["Date"].apply(convert_date)

print(df["Date"].isna().sum())

0

In [ ]:
df["Amount"] = (
    df["Amount"]
    .astype(str)
    .str.replace("₹","",regex=False)
    .str.replace("Rs.","",regex=False)
    .str.replace(",","",regex=False)
    .str.strip()
)

df["Amount"] = pd.to_numeric(df["Amount"])

print(df["Amount"].head())

0     2462.0
1       50.0
2    84728.0
3     1828.0
4      270.0
Name: Amount, dtype: float64

In [ ]:
df["Type"] = (
    df["Type"]
    .astype(str)
    .str.strip()
    .str.upper()
)

df["Type"] = df["Type"].replace({
    "DR":"Debit",
    "CR":"Credit"
})

print(df["Type"].value_counts())

Type
Debit     670
DEBIT     652
Credit      6
Name: count, dtype: int64

In [ ]:
print("Duplicates Before:",df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicates After:",df.duplicated().sum())

Duplicates Before: 18
Duplicates After: 0

In [ ]:
vendor_dict = {
    "Amazon": ["AMAZON", "AMZN"],
    "Amazon Pay": ["AMAZONPAY"],
    "Swiggy": ["SWIGGY", "BUNDL"],
    "Zomato": ["ZOMATO"],
    "Blinkit": ["BLINKIT", "GROFERS"],
    "Zepto": ["ZEPTO"],
    "Instamart": ["INSTAMART"],
    "BigBasket": ["BIGBASKET", "KIRANAKART"],
    "DMart": ["DMART", "AVENUE SUPERMARTS"],
    "Flipkart": ["FLIPKART", "FKART"],
    "Myntra": ["MYNTRA"],
    "Nykaa": ["NYKAA", "FSN E-COMMERCE"],
    "Uber": ["UBER"],
    "Ola": ["OLA", "ANI TECHNOLOGIES"],
    "Rapido": ["RAPIDO"],
    "BMTC": ["BMTC", "TUMMOC"],
    "Starbucks": ["STARBUCKS"],
    "Third Wave": ["THIRDWAVE", "TWC INDIA"],
    "Cafe Coffee Day": ["CCD", "COFFEE DAY"],
    "Truffles": ["TRUFFLES"],
    "Empire": ["EMPIRE"],
    "Meghana Foods": ["MEGHANA"],
    "Restaurant": ["RESTAURANT"],
    "BookMyShow": ["BMS", "BIGTREE"],
    "Netflix": ["NETFLIX"],
    "Spotify": ["SPOTIFY"],
    "Hotstar": ["HOTSTAR", "STAR INDIA"],
    "Groww": ["GROWW", "NEXTBILLION"],
    "Zerodha": ["ZERODHA"],
    "Salary": ["SALARY"],
    "Rent": ["RENT"],
    "Jio": ["JIO", "JIOFIBER"],
    "Airtel": ["AIRTEL", "BHARTI"],
    "Vi": ["VI POSTPAID", "VI-RECHARGE"],
    "BESCOM": ["BESCOM", "BANGALORE ELEC"],
    "BWSSB": ["BWSSB"],
    "Indian Oil": ["IOC", "INDIAN OIL"],
    "HP Petrol": ["HP PETROL"],
    "BPCL": ["BPCL"],
    "Cash Withdrawal": ["ATM-WDL"],
    "P2P Transfer": ["@OKAXIS", "@OKICICI", "@PAYTM", "@HDFCBANK"]
}

In [ ]:
df["Vendor"] = df["Description"].apply(extract_vendor)

In [ ]:
def extract_vendor(description):

    description = str(description).upper()

    for vendor,keywords in vendor_dict.items():

        for keyword in keywords:

            if keyword in description:

                return vendor

    return "Unknown"

df["Vendor"] = df["Description"].apply(extract_vendor)

print(df["Vendor"].value_counts())

Vendor
Swiggy             223
Zomato             121
Ola                 87
Amazon              86
Uber                71
Zepto               58
Blinkit             55
Flipkart            47
Unknown             45
Starbucks           42
Rapido              41
BMTC                37
Restaurant          29
Cafe Coffee Day     26
BigBasket           24
P2P Transfer        22
DMart               22
Myntra              20
Third Wave          20
Instamart           20
Nykaa               19
Cash Withdrawal     17
Indian Oil          17
BESCOM              15
Zerodha             14
Empire              13
Hotstar             13
Meghana Foods       12
Netflix             10
HP Petrol            9
Groww                9
BookMyShow           9
Truffles             9
Spotify              8
BWSSB                8
Salary               6
Jio                  6
Rent                 6
Airtel               6
Vi                   6
BPCL                 2
Name: count, dtype: int64

In [ ]:
category_dict.update({
    "Flipkart":"E-Commerce",
    "Myntra":"E-Commerce",
    "Nykaa":"E-Commerce",
    "Amazon Pay":"Payments",

    "BigBasket":"Quick Commerce",
    "DMart":"Groceries",

    "Rapido":"Transport",

    "Restaurant":"Dining",
    "Truffles":"Dining",
    "Empire":"Dining",
    "Meghana Foods":"Dining",

    "Netflix":"Subscription",
    "Spotify":"Subscription",
    "Hotstar":"Subscription",

    "Jio":"Utilities",
    "Airtel":"Utilities",
    "Vi":"Utilities",
    "BESCOM":"Utilities",
    "BWSSB":"Utilities",

    "Indian Oil":"Fuel",
    "HP Petrol":"Fuel",
    "BPCL":"Fuel",

    "Rent":"Housing"
})

df["Category"] = df["Vendor"].map(category_dict).fillna("Others")

In [ ]:
df["Month"] = df["Date"].dt.month_name()

print(df[["Date","Month"]].head())

        Date    Month
0 2024-01-01  January
1 2024-01-01  January
2 2024-01-01  January
3 2024-01-01  January
4 2024-01-01  January

In [ ]:
total_credit = df[df["Type"]=="Credit"]["Amount"].sum()

total_debit = df[df["Type"]=="Debit"]["Amount"].sum()

net_savings = total_credit-total_debit

print("Total Credit :",total_credit)

print("Total Debit :",total_debit)

print("Net Savings :",net_savings)

Total Credit : 509774.0
Total Debit : 821046.0
Net Savings : -311272.0

In [ ]:
top_categories = (
    df.groupby("Category")["Amount"]
    .sum()
    .sort_values(ascending=False)
)

print(top_categories)

Category
Others               699584.0
Income               509774.0
E-Commerce           328530.0
Investment           248160.0
Food Delivery        150839.0
Personal Transfer     71849.0
Quick Commerce        60089.0
Transport             51717.0
Cash                  45500.0
Cafe                  18552.0
Entertainment          4081.0
Name: Amount, dtype: float64

In [ ]:
top_vendors = (
    df.groupby("Vendor")["Amount"]
    .sum()
    .sort_values(ascending=False)
)

print(top_vendors.head(10))

Vendor
Unknown            699584.0
Salary             509774.0
Amazon             328530.0
Zerodha            210000.0
Swiggy              95523.0
P2P Transfer        71849.0
Zomato              55316.0
Cash Withdrawal     45500.0
Groww               38160.0
Zepto               28157.0
Name: Amount, dtype: float64

In [ ]:
monthly_spending = (
    df.groupby("Month")["Amount"]
    .sum()
)

print(monthly_spending)

Month
April       336118.0
February    318795.0
January     375495.0
June        380409.0
March       415159.0
May         362699.0
Name: Amount, dtype: float64

In [ ]:
monthly_category = pd.pivot_table(
    df,
    values="Amount",
    index="Category",
    columns="Month",
    aggfunc="sum",
    fill_value=0
)

print(monthly_category)

Month                 April  February   January      June     March       May
Category
Cafe                 3465.0    2312.0    1895.0    3870.0    3016.0    3994.0
Cash                 5500.0    5000.0    2000.0   17000.0    8000.0    8000.0
E-Commerce          26912.0   64264.0   45693.0   87308.0   87050.0   17303.0
Entertainment           0.0       0.0     311.0    1914.0    1856.0       0.0
Food Delivery       27756.0   23740.0   22633.0   26499.0   24803.0   25408.0
Income              84736.0   84724.0   84728.0   85492.0   84701.0   85393.0
Investment          54126.0   15000.0   38432.0   23330.0   68644.0   48628.0
Others             107281.0   88349.0  142931.0  110493.0  107241.0  143289.0
Personal Transfer    8265.0   13000.0   18953.0   11395.0   10435.0    9801.0
Quick Commerce       9845.0   13899.0    8110.0    6772.0   13344.0    8119.0
Transport            8232.0    8507.0    9809.0    6336.0    6069.0   12764.0

In [ ]:
df["Hour"] = df["Time"].str[:2].astype(int)

print(df[["Time","Hour"]].head())

    Time  Hour
0  03:11     3
1  05:44     5
2  09:35     9
3  14:07    14
4  14:23    14

In [ ]:
hourly_spending = (
    df.groupby("Hour")["Amount"]
    .sum()
)

print(hourly_spending)

Hour
0      37969.0
1      38882.0
2      20283.0
3      34868.0
4      43901.0
5      33671.0
6      55506.0
7      19938.0
8      41399.0
9     596475.0
10    140526.0
11    123389.0
12     77096.0
13    113819.0
14    121010.0
15     39647.0
16    100597.0
17     56604.0
18    101343.0
19     67848.0
20    138089.0
21     81545.0
22     55867.0
23     48403.0
Name: Amount, dtype: float64

In [ ]:
late_food = df[
    (df["Category"]=="Food Delivery")
    &
    (df["Hour"]>=21)
]

print(late_food)

           Date   Time                  Description   Type  Amount   Balance  \
23   2024-01-03  23:58        POS SWIGGY-RESTAURANT  DEBIT   238.0  666548.0
39   2024-01-05  21:30                   POS ZOMATO  Debit   695.0  652234.0
64   2024-01-08  21:23               BUNDL Tech P L  Debit   238.0  644405.0
141  2024-01-20  23:53     UPI-SWIGGY-9474@HDFCBANK  DEBIT   181.0  561646.0
151  2024-01-22  21:47     UPI-SWIGGY-2954@HDFCBANK  Debit   254.0  554681.0
...         ...    ...                          ...    ...     ...       ...
1198 2024-06-12  23:36  UPI-SWIGGY-INSTAMART@OKAXIS  Debit   225.0 -230142.0
1211 2024-06-14  21:37                ZOMATO-DINING  Debit   632.0 -242175.0
1219 2024-06-15  22:55                 Swiggy*Order  DEBIT   425.0 -246766.0
1250 2024-06-19  21:57               BUNDL Tech P L  DEBIT   404.0 -266852.0
1313 2024-06-28  21:33               BUNDL Tech P L  Debit   589.0 -307229.0

     Mode        Ref  Vendor       Category    Month  Hour
23    UPI  TXN975271  Swiggy  Food Delivery  January    23
39    UPI  TXN809176  Zomato  Food Delivery  January    21
64    UPI  TXN827157  Swiggy  Food Delivery  January    21
141   UPI  TXN462974  Swiggy  Food Delivery  January    23
151   UPI  TXN697467  Swiggy  Food Delivery  January    21
...   ...        ...     ...            ...      ...   ...
1198  UPI  TXN385173  Swiggy  Food Delivery     June    23
1211  UPI  TXN734604  Zomato  Food Delivery     June    21
1219  UPI  TXN942918  Swiggy  Food Delivery     June    22
1250  UPI  TXN357284  Swiggy  Food Delivery     June    21
1313  UPI  TXN356161  Swiggy  Food Delivery     June    21

[61 rows x 12 columns]

In [ ]:
mean = df.groupby("Category")["Amount"].transform("mean")

std = df.groupby("Category")["Amount"].transform("std")

df["z_score"] = (df["Amount"]-mean)/std

anomalies = df[df["z_score"]>2]

print(anomalies[["Date","Vendor","Category","Amount","z_score"]])

           Date         Vendor        Category   Amount   z_score
49   2024-01-07     Restaurant          Dining   7314.0  3.415271
160  2024-01-23      BigBasket  Quick Commerce   1797.0  4.374408
169  2024-01-24       Flipkart      E-Commerce  16260.0  2.819266
171  2024-01-24     Indian Oil            Fuel  10408.0  2.246441
218  2024-01-31      BigBasket  Quick Commerce   1258.0  2.480946
269  2024-02-07         Amazon      E-Commerce  21986.0  4.085484
335  2024-02-17      BigBasket  Quick Commerce   1517.0  3.390791
336  2024-02-17         Amazon      E-Commerce  13674.0  2.247412
350  2024-02-19      BigBasket  Quick Commerce   1293.0  2.603898
414  2024-02-26     Restaurant          Dining   8383.0  4.049130
450  2024-03-02         Amazon      E-Commerce  18273.0  3.264410
464  2024-03-04       Truffles          Dining   7441.0  3.490575
475  2024-03-05         Amazon      E-Commerce  19917.0  3.627956
522  2024-03-12      BigBasket  Quick Commerce   1865.0  4.613286
541  2024-03-14     Indian Oil            Fuel  10505.0  2.276628
589  2024-03-21         Swiggy   Food Delivery    825.0  2.514304
651  2024-03-31         Amazon      E-Commerce  15953.0  2.751378
653  2024-03-31  Meghana Foods          Dining   7931.0  3.781118
699  2024-04-05       Flipkart      E-Commerce  14305.0  2.386948
744  2024-04-12         Swiggy   Food Delivery    829.0  2.540325
761  2024-04-14         Swiggy   Food Delivery    824.0  2.507799
792  2024-04-18      BigBasket  Quick Commerce   1518.0  3.394304
875  2024-04-30         Amazon      E-Commerce  14886.0  2.515427
984  2024-05-15       Flipkart      E-Commerce  14416.0  2.411494
1076 2024-05-26         Swiggy   Food Delivery    821.0  2.488284
1079 2024-05-27       Flipkart      E-Commerce  17831.0  3.166669
1130 2024-06-03       Flipkart      E-Commerce  16369.0  2.843370
1144 2024-06-05         Amazon      E-Commerce  14874.0  2.512773
1207 2024-06-13         Swiggy   Food Delivery    833.0  2.566345
1271 2024-06-22        Unknown          Others   7935.0  7.246036
1291 2024-06-25         Amazon      E-Commerce  17504.0  3.094358
1298 2024-06-26         Amazon      E-Commerce  22008.0  4.090349
1308 2024-06-27       Flipkart      E-Commerce  15955.0  2.751820

In [ ]:
df["Hour"] = df["Time"].str[:2].astype(int)

df[["Time","Hour"]].head()

    Time  Hour
0  03:11     3
1  05:44     5
2  09:35     9
3  14:07    14
4  14:23    14

In [ ]:
def time_slot(hour):

    if 5 <= hour < 12:
        return "Morning"

    elif 12 <= hour < 17:
        return "Afternoon"

    elif 17 <= hour < 21:
        return "Evening"

    else:
        return "Night"

df["Time Slot"] = df["Hour"].apply(time_slot)

In [ ]:
time_analysis = df.groupby("Time Slot")["Amount"].sum()

print(time_analysis)

Time Slot
Afternoon     452169.0
Evening       363884.0
Morning      1010904.0
Night         361718.0
Name: Amount, dtype: float64

In [ ]:
late_food = df[
    (df["Category"]=="Food Delivery") &
    (df["Hour"]>=21)
]

print(late_food[["Date","Vendor","Amount","Hour"]])

           Date  Vendor  Amount  Hour
23   2024-01-03  Swiggy   238.0    23
39   2024-01-05  Zomato   695.0    21
64   2024-01-08  Swiggy   238.0    21
141  2024-01-20  Swiggy   181.0    23
151  2024-01-22  Swiggy   254.0    21
...         ...     ...     ...   ...
1198 2024-06-12  Swiggy   225.0    23
1211 2024-06-14  Zomato   632.0    21
1219 2024-06-15  Swiggy   425.0    22
1250 2024-06-19  Swiggy   404.0    21
1313 2024-06-28  Swiggy   589.0    21

[61 rows x 4 columns]

In [ ]:
food = df[df["Category"]=="Food Delivery"]

late_percent = (len(late_food)/len(food))*100

print("Late Night Food Orders:",round(late_percent,2),"%")

Late Night Food Orders: 17.73 %

In [ ]:
mean = df.groupby("Category")["Amount"].transform("mean")

std = df.groupby("Category")["Amount"].transform("std")

df["Z Score"] = (df["Amount"]-mean)/std

In [ ]:
anomalies = df[df["Z Score"]>2]

anomalies = anomalies.sort_values("Z Score",ascending=False)

anomalies[["Date","Vendor","Category","Amount","Z Score"]]

           Date         Vendor        Category   Amount   Z Score
1271 2024-06-22        Unknown          Others   7935.0  7.246036
522  2024-03-12      BigBasket  Quick Commerce   1865.0  4.613286
160  2024-01-23      BigBasket  Quick Commerce   1797.0  4.374408
1298 2024-06-26         Amazon      E-Commerce  22008.0  4.090349
269  2024-02-07         Amazon      E-Commerce  21986.0  4.085484
414  2024-02-26     Restaurant          Dining   8383.0  4.049130
653  2024-03-31  Meghana Foods          Dining   7931.0  3.781118
475  2024-03-05         Amazon      E-Commerce  19917.0  3.627956
464  2024-03-04       Truffles          Dining   7441.0  3.490575
49   2024-01-07     Restaurant          Dining   7314.0  3.415271
792  2024-04-18      BigBasket  Quick Commerce   1518.0  3.394304
335  2024-02-17      BigBasket  Quick Commerce   1517.0  3.390791
450  2024-03-02         Amazon      E-Commerce  18273.0  3.264410
1079 2024-05-27       Flipkart      E-Commerce  17831.0  3.166669
1291 2024-06-25         Amazon      E-Commerce  17504.0  3.094358
1130 2024-06-03       Flipkart      E-Commerce  16369.0  2.843370
169  2024-01-24       Flipkart      E-Commerce  16260.0  2.819266
1308 2024-06-27       Flipkart      E-Commerce  15955.0  2.751820
651  2024-03-31         Amazon      E-Commerce  15953.0  2.751378
350  2024-02-19      BigBasket  Quick Commerce   1293.0  2.603898
1207 2024-06-13         Swiggy   Food Delivery    833.0  2.566345
744  2024-04-12         Swiggy   Food Delivery    829.0  2.540325
875  2024-04-30         Amazon      E-Commerce  14886.0  2.515427
589  2024-03-21         Swiggy   Food Delivery    825.0  2.514304
1144 2024-06-05         Amazon      E-Commerce  14874.0  2.512773
761  2024-04-14         Swiggy   Food Delivery    824.0  2.507799
1076 2024-05-26         Swiggy   Food Delivery    821.0  2.488284
218  2024-01-31      BigBasket  Quick Commerce   1258.0  2.480946
984  2024-05-15       Flipkart      E-Commerce  14416.0  2.411494
699  2024-04-05       Flipkart      E-Commerce  14305.0  2.386948
541  2024-03-14     Indian Oil            Fuel  10505.0  2.276628
336  2024-02-17         Amazon      E-Commerce  13674.0  2.247412
171  2024-01-24     Indian Oil            Fuel  10408.0  2.246441

In [ ]:
print(anomalies.head(10))

           Date   Time               Description   Type   Amount   Balance  \
1271 2024-06-22  12:46               POS DINEOUT  DEBIT   7935.0 -480815.0
522  2024-03-12  11:19       BIGBASKET BANGALORE  DEBIT   1865.0  291976.0
160  2024-01-23  21:36    UPI-BIGBASKET@HDFCBANK  Debit   1797.0  546871.0
1298 2024-06-26  09:07      AMAZONIN MARKETPLACE  Debit  22008.0 -699028.0
269  2024-02-07  17:28    UPI-AMAZONPAY@HDFCBANK  DEBIT  21986.0 -360151.0
414  2024-02-26  20:09  POS BANGALORE RESTAURANT  Debit   8383.0 -567033.0
653  2024-03-31  20:01         POS MEGHANA FOODS  Debit   7931.0 -445522.0
475  2024-03-05  21:33    UPI-AMAZONPAY@HDFCBANK  DEBIT  19917.0 -465439.0
464  2024-03-04  16:12              POS TRUFFLES  Debit   7441.0 -472880.0
49   2024-01-07  08:38  POS BANGALORE RESTAURANT  DEBIT   7314.0 -411932.0

     Mode        Ref         Vendor        Category     Month  Hour   z_score  \
1271  UPI  TXN540191        Unknown          Others      June    12  7.246036
522   UPI  TXN880623      BigBasket  Quick Commerce     March    11  4.613286
160   UPI  TXN517643      BigBasket  Quick Commerce   January    21  4.374408
1298  UPI  TXN313051         Amazon      E-Commerce      June     9  4.090349
269   UPI  TXN988380         Amazon      E-Commerce  February    17  4.085484
414   UPI  TXN308266     Restaurant          Dining  February    20  4.049130
653   UPI  TXN149269  Meghana Foods          Dining     March    20  3.781118
475   UPI  TXN674071         Amazon      E-Commerce     March    21  3.627956
464   UPI  TXN830484       Truffles          Dining     March    16  3.490575
49    UPI  TXN388441     Restaurant          Dining   January     8  3.415271

      Time Slot   Z Score
1271  Afternoon  7.246036
522     Morning  4.613286
160       Night  4.374408
1298    Morning  4.090349
269     Evening  4.085484
414     Evening  4.049130
653     Evening  3.781118
475       Night  3.627956
464   Afternoon  3.490575
49      Morning  3.415271

In [ ]:
category_spend = df.groupby("Category")["Amount"].sum()

total_spend = category_spend.sum()

category_percent = (category_spend/total_spend)*100

print(category_percent)

Category
Cafe                  0.997955
Cash                  2.078883
Dining                4.473574
E-Commerce           27.590985
Entertainment         0.255908
Food Delivery         6.891795
Fuel                  4.080231
Groceries             1.711675
Housing               4.934492
Income               23.291443
Investment           11.338367
Others                1.890961
Personal Transfer     1.246919
Quick Commerce        3.957965
Subscription          0.843935
Transport             2.553326
Utilities             1.861583
Name: Amount, dtype: float64

In [ ]:
archetypes = []

In [ ]:
if category_percent.get("Food Delivery",0)>25:
    archetypes.append("THE FOODIE")

In [ ]:
if category_percent.get("Quick Commerce",0)>15:
    archetypes.append("THE QUICK COMMERCE")

In [ ]:
if category_percent.get("E-Commerce",0)>15:
    archetypes.append("THE SHOPAHOLIC")

In [ ]:
if category_percent.get("Investment",0)>10:
    archetypes.append("THE INVESTOR")

In [ ]:
if net_savings<0:
    archetypes.append("THE YOLO SPENDER")

In [ ]:
print("SPENDING ARCHETYPES")

for i in archetypes:
    print("->",i)

SPENDING ARCHETYPES
-> THE SHOPAHOLIC
-> THE INVESTOR
-> THE YOLO SPENDER

In [ ]:
print("="*60)

print("            SPENDDNA REPORT")

print("="*60)

print()

print("Total Income :",total_credit)

print("Total Expense :",total_debit)

print("Net Savings :",net_savings)

print()

print("="*60)

print("TOP CATEGORIES")

print(top_categories)

print()

print("="*60)

print("TOP VENDORS")

print(top_vendors.head(10))

print()

print("="*60)

print("MONTHLY SPENDING")

print(monthly_spending)

print()

print("="*60)

print("TIME OF DAY")

print(time_analysis)

print()

print("="*60)

print("TOP ANOMALIES")

print(anomalies.head(10))

print()

print("="*60)

print("SPENDING ARCHETYPES")

for i in archetypes:
    print("->",i)

print("="*60)

============================================================
            SPENDDNA REPORT
============================================================

Total Income : 509774.0
Total Expense : 821046.0
Net Savings : -311272.0

============================================================
TOP CATEGORIES
Category
Others               699584.0
Income               509774.0
E-Commerce           328530.0
Investment           248160.0
Food Delivery        150839.0
Personal Transfer     71849.0
Quick Commerce        60089.0
Transport             51717.0
Cash                  45500.0
Cafe                  18552.0
Entertainment          4081.0
Name: Amount, dtype: float64

============================================================
TOP VENDORS
Vendor
Unknown            699584.0
Salary             509774.0
Amazon             328530.0
Zerodha            210000.0
Swiggy              95523.0
P2P Transfer        71849.0
Zomato              55316.0
Cash Withdrawal     45500.0
Groww               38160.0
Zepto               28157.0
Name: Amount, dtype: float64

============================================================
MONTHLY SPENDING
Month
April       336118.0
February    318795.0
January     375495.0
June        380409.0
March       415159.0
May         362699.0
Name: Amount, dtype: float64

============================================================
TIME OF DAY
Time Slot
Afternoon     452169.0
Evening       363884.0
Morning      1010904.0
Night         361718.0
Name: Amount, dtype: float64

============================================================
TOP ANOMALIES
           Date   Time               Description   Type   Amount   Balance  \
1271 2024-06-22  12:46               POS DINEOUT  DEBIT   7935.0 -480815.0
522  2024-03-12  11:19       BIGBASKET BANGALORE  DEBIT   1865.0  291976.0
160  2024-01-23  21:36    UPI-BIGBASKET@HDFCBANK  Debit   1797.0  546871.0
1298 2024-06-26  09:07      AMAZONIN MARKETPLACE  Debit  22008.0 -699028.0
269  2024-02-07  17:28    UPI-AMAZONPAY@HDFCBANK  DEBIT  21986.0 -360151.0
414  2024-02-26  20:09  POS BANGALORE RESTAURANT  Debit   8383.0 -567033.0
653  2024-03-31  20:01         POS MEGHANA FOODS  Debit   7931.0 -445522.0
475  2024-03-05  21:33    UPI-AMAZONPAY@HDFCBANK  DEBIT  19917.0 -465439.0
464  2024-03-04  16:12              POS TRUFFLES  Debit   7441.0 -472880.0
49   2024-01-07  08:38  POS BANGALORE RESTAURANT  DEBIT   7314.0 -411932.0

     Mode        Ref         Vendor        Category     Month  Hour   z_score  \
1271  UPI  TXN540191        Unknown          Others      June    12  7.246036
522   UPI  TXN880623      BigBasket  Quick Commerce     March    11  4.613286
160   UPI  TXN517643      BigBasket  Quick Commerce   January    21  4.374408
1298  UPI  TXN313051         Amazon      E-Commerce      June     9  4.090349
269   UPI  TXN988380         Amazon      E-Commerce  February    17  4.085484
414   UPI  TXN308266     Restaurant          Dining  February    20  4.049130
653   UPI  TXN149269  Meghana Foods          Dining     March    20  3.781118
475   UPI  TXN674071         Amazon      E-Commerce     March    21  3.627956
464   UPI  TXN830484       Truffles          Dining     March    16  3.490575
49    UPI  TXN388441     Restaurant          Dining   January     8  3.415271

      Time Slot   Z Score
1271  Afternoon  7.246036
522     Morning  4.613286
160       Night  4.374408
1298    Morning  4.090349
269     Evening  4.085484
414     Evening  4.049130
653     Evening  3.781118
475       Night  3.627956
464   Afternoon  3.490575
49      Morning  3.415271

============================================================
SPENDING ARCHETYPES
-> THE SHOPAHOLIC
-> THE INVESTOR
-> THE YOLO SPENDER
============================================================

In [ ]:
print("\nKEY INSIGHTS")

print("1. Highest spending category :",top_categories.idxmax())

print("2. Favourite vendor :",top_vendors.idxmax())

print("3. Net Savings :",net_savings)

print("4. Late Night Food Orders :",round(late_percent,2),"%")

print("5. Total Anomalies :",len(anomalies))

KEY INSIGHTS
1. Highest spending category : Others
2. Favourite vendor : Unknown
3. Net Savings : -311272.0
4. Late Night Food Orders : 17.73 %
5. Total Anomalies : 33

In [ ]:
# Export the final cleaned dataset
df.to_csv("SpendDNA_Final_Dataset.csv", index=False)

print("✅ File exported successfully as SpendDNA_Final_Dataset.csv")

✅ File exported successfully as SpendDNA_Final_Dataset.csv

In [ ]:
with pd.ExcelWriter("SpendDNA_Report.xlsx") as writer:

    # Main cleaned dataset
    df.to_excel(writer, sheet_name="Cleaned Data", index=False)

    # Top Categories
    top_categories.to_frame(name="Amount").to_excel(
        writer,
        sheet_name="Top Categories"
    )

    # Top Vendors
    top_vendors.to_excel(
        writer,
        sheet_name="Top Vendors"
    )

    # Monthly Spending
    monthly_spending.to_frame(name="Amount").to_excel(
        writer,
        sheet_name="Monthly Spending"
    )

    # Monthly Category Pivot
    monthly_category.to_excel(
        writer,
        sheet_name="Monthly Category"
    )

    # Time Analysis
    time_analysis.to_frame(name="Amount").to_excel(
        writer,
        sheet_name="Time Analysis"
    )

    # Anomalies
    anomalies.to_excel(
        writer,
        sheet_name="Anomalies",
        index=False
    )

print("✅ SpendDNA_Report.xlsx created successfully!")

✅ SpendDNA_Report.xlsx created successfully!